### ISSUE TITLE
plugin defect or obsolete ?

### ISSUE THREAD

**Issue by 5mart4zz** [alexlittle/moodle-block_online_users_map#11]
Hi, I tried to install this plugin on moodle 3.10 and it did not work, with error message at installation process.
I noticed that there was not much activity on this plugin in the last few years but I wanted to try anyway as I find the feature very interesting.

Is there a chance that this plugin may be updated someday ?

**Comment by alexlittle** [comment]
Hi @5mart4zz 
I'm not so surprised that it's not working with the current version of Moodle, since I think I last used it with Moodle 2.x, so very long time ago now and am sure quite a bit  has changed. 
At the moment I have no plans for updating the plugin for more recent versions of Moodle, but very happy if someone would like to make updates (it's open source after all), either directly by sending pull requests to me, or creating a new fork on github,
Cheers,
Alex
